git-debimport pacemaker_1.1.16.orig.tar.gz

diff --git a/doc/Makefile.am b/doc/Makefile.am
--- a/doc/Makefile.am
+++ b/doc/Makefile.am
@@ -22,11 +22,18 @@ include $(top_srcdir)/Makefile.common
 helpdir		= $(datadir)/$(PACKAGE)
 
 ascii		= crm_fencing.txt acls.txt
-docbook		= Pacemaker_Explained Clusters_from_Scratch Pacemaker_Remote
+docbook		= Clusters_from_Scratch \
+	Pacemaker_Development \
+	Pacemaker_Explained \
+	Pacemaker_Remote
 doc_DATA	= $(ascii) $(generated_docs)
 
-# rsync destination for www targets
-RSYNC_DEST      = root@www.clusterlabs.org:/var/www/html/doc/
+# toplevel rsync destination for www targets (without trailing slash)
+RSYNC_DEST      ?= root@www.clusterlabs.org:/var/www/html/
+
+# recursive, preserve symlinks/permissions/times, verbose, compress,
+# don't cross filesystems, sparse, show progress
+RSYNC_OPTS      = -rlptvzxS --progress
 
 publican_docs   =
 generated_docs	=
@@ -116,6 +123,29 @@ endif
 # We have to hardcode the book name
 # With '%' the test for 'newness' fails
 Clusters_from_Scratch.build: $(PNGS) $(wildcard Clusters_from_Scratch/en-US/*.xml) $(CFS_XML) $(CFS_SHARED_XML) $(PUBLICAN_INTREE_DEPS)
+	$(PCMK_V) @echo Building $(@:%.build=%) because of $?
+	rm -rf $(@:%.build=%)/publish/*
+if PUBLICAN_INTREE_BRAND
+	$(AM_V_PUB)cd $(@:%.build=%) \
+	&& RPM_BUILD_DIR="" XML_CATALOG_FILES="$(CURDIR)/publican-catalog" \
+	   $(PUBLICAN) build --publish --langs=$(DOCBOOK_LANGS) --formats=$(DOCBOOK_FORMATS) --brand_dir=../publican-clusterlabs \
+	   $(PCMK_quiet)
+else
+	$(AM_V_PUB)cd $(@:%.build=%) \
+	&& RPM_BUILD_DIR="" \
+	   $(PUBLICAN) build --publish --langs=$(DOCBOOK_LANGS) --formats=$(DOCBOOK_FORMATS) \
+	   $(PCMK_quiet)
+endif
+	rm -rf $(@:%.build=%)/tmp
+	touch $@
+
+
+PD_TXT=$(wildcard Pacemaker_Development/en-US/*.txt)
+PD_XML=$(PD_TXT:%.txt=%.xml)
+
+# We have to hardcode the book name
+# With '%' the test for 'newness' fails
+Pacemaker_Development.build: $(wildcard Pacemaker_Development/en-US/*.xml) $(PD_XML) $(PUBLICAN_INTREE_DEPS)
 	$(PCMK_V) @echo Building $(@:%.build=%) because of $?
 	rm -rf $(@:%.build=%)/publish/*
 if PUBLICAN_INTREE_BRAND
@@ -229,7 +259,7 @@ pdf:
 
 www: clean-local $(generated_docs) $(ascii)
 	make www-cli
-	rsync -rtz --progress $(generated_docs) $(ascii) $(asciiman) $(RSYNC_DEST)
+	rsync $(RSYNC_OPTS) $(generated_docs) $(ascii) $(asciiman) "$(RSYNC_DEST)/doc/"
 
 www-pcs: www-cli
 
@@ -248,7 +278,7 @@ if BUILD_DOCBOOK
 			mv $$book/publish/$$lang/Pacemaker/$(PACKAGE_SERIES)-$(ASCIIDOC_CLI_TYPE)/epub/$$book/Pacemaker-1.1{-$(ASCIIDOC_CLI_TYPE),}-$$book-$$lang.epub;	\
 			mv $$book/publish/$$lang/Pacemaker/$(PACKAGE_SERIES)-$(ASCIIDOC_CLI_TYPE)/pdf/$$book/Pacemaker-1.1{-$(ASCIIDOC_CLI_TYPE),}-$$book-$$lang.pdf;	\
 		done;											\
-		rsync -rtz --progress $$book/publish/* $(RSYNC_DEST);					\
+		rsync $(RSYNC_OPTS) $$book/publish/* "$(RSYNC_DEST)/doc/";				\
 		sed -i.sed 's@version:.*@version: $(PACKAGE_SERIES)@' $$book/publican.cfg;		\
 	done
 endif
