git-debimport pacemaker_1.1.14.orig.tar.gz

diff --git a/doc/Makefile.am b/doc/Makefile.am
--- a/doc/Makefile.am
+++ b/doc/Makefile.am
@@ -7,32 +7,45 @@
 # modify it under the terms of the GNU General Public License
 # as published by the Free Software Foundation; either version 2
 # of the License, or (at your option) any later version.
-# 
+#
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
-# 
+#
 # You should have received a copy of the GNU General Public License
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 #
-MAINTAINERCLEANFILES    = Makefile.in
+include $(top_srcdir)/Makefile.common
 
 helpdir		= $(datadir)/$(PACKAGE)
 
-ascii		= crm_cli.txt crm_fencing.txt
-help_DATA	= crm_cli.txt
-docbook		= Pacemaker_Explained
-man_MANS	= cibadmin.8 crm_resource.8
-doc_DATA	= README.hb2openais $(ascii) $(generated_docs)
+ascii		= crm_fencing.txt acls.txt
+docbook		= Pacemaker_Explained Clusters_from_Scratch Pacemaker_Remote
+doc_DATA	= $(ascii) $(generated_docs)
 
-publican_docs    =
-generated_docs	= 
+# rsync destination for www targets
+RSYNC_DEST      = root@www.clusterlabs.org:/var/www/html/doc/
 
-SVG := $(wildcard */en-US/images/pcmk-*.svg)
+publican_docs   =
+generated_docs	=
+generated_mans	=
 
-PNGS = $(SVG:%.svg=%-small.png) $(SVG:%.svg=%.png)  $(SVG:%.svg=%-large.png)	\
+ASCIIDOC_CLI_TYPE := pcs
+DOCBOOK_FORMATS := html-desktop
+DOCBOOK_LANGS   := en-US
+DOTs = $(wildcard */en-US/images/*.dot)
+SVG = $(wildcard */en-US/images/pcmk-*.svg) $(DOTs:%.dot=%.svg)
+
+generated_PNGS = $(SVG:%.svg=%-small.png) $(SVG:%.svg=%.png)  $(SVG:%.svg=%-large.png) 	\
+	Pacemaker_Explained/en-US/images/Policy-Engine-big.png  \
+	Pacemaker_Explained/en-US/images/Policy-Engine-small.png
+PNGS = $(generated_PNGS) \
+	Pacemaker_Remote/en-US/images/pcmk-ha-cluster-stack.png \
+	Pacemaker_Remote/en-US/images/pcmk-ha-remote-stack.png
+
+BRAND_PNGS = publican-clusterlabs/en-US/images/title_logo.png			\
 	publican-clusterlabs/en-US/images/image_left.png			\
 	publican-clusterlabs/en-US/images/image_right.png			\
 	publican-clusterlabs/en-US/images/h1-bg.png
@@ -40,88 +53,154 @@ PNGS = $(SVG:%.svg=%-small.png) $(SVG:%.svg=%.png)  $(SVG:%.svg=%-large.png)	\
 graphics: $(PNGS)
 
 %.png: %.svg
-	inkscape --file=$< --export-dpi=90 -C --export-png=$@
+	$(AM_V_IMG)$(INKSCAPE) --file=$< --export-dpi=90 -C --export-png=$@
 
 %-small.png: %.svg
-	inkscape --file=$< --export-dpi=45 -C --export-png=$@
+	$(AM_V_IMG)$(INKSCAPE) --file=$< --export-dpi=45 -C --export-png=$@
 
 %-large.png: %.svg
-	inkscape --file=$< --export-dpi=180 -C --export-png=$@
-
-XML_FILES := $(wildcard *.xml)
-PNG_FILES := $(wildcard images/*.png)
+	$(AM_V_IMG)$(INKSCAPE) --file=$< --export-dpi=180 -C --export-png=$@
 
 if BUILD_ASCIIDOC
 generated_docs	+= $(ascii:%.txt=%.html)
-endif
 
 if BUILD_DOCBOOK
 publican_docs	+= $(docbook)
 endif
-
-EXTRA_DIST	= $(man_MANS) $(docbook:%=%.xml) 
-
-index.html: 
-	echo "Building documentation index"
-	echo "<html><body><p>The following <a href=\"http://www.clusterlabs.org/wiki/Pacemaker\">Pacemaker</a> documentation was generated on `date` from version: $(BUILD_VERSION)</p>" > index.html	
-	echo "<ol>" >> index.html
-	for doc in $(generated_docs); do 					\
-		echo "<li><a href=\"$$doc\">$$doc</a></li>" >> index.html; 	\
-	done
-if BUILD_DOCBOOK
-	for book in $(docbook); do 					\
-	    for lang in `ls -1 $(docbook)/publish`; do 			\
-	      echo "<li>$$book ($$lang)<ul>" >> index.html; 	\
-	      find $$book/publish/$$lang -name "*.pdf" -exec echo -n "<li><a href=\"{}\">" \; -exec basename {} \; -exec echo "</a></li>" \; | sed s:$$book/publish/:: >> index.html ;		\
-	      find $$book/publish/$$lang -name "*.txt" -exec echo -n "<li><a href=\"{}\">" \; -exec basename {} \; -exec echo "</a></li>" \; | sed s:$$book/publish/:: >> index.html ;		\
-	      find $$book/publish/$$lang -name html -exec echo "<li><a href=\"{}/$$book/index.html\">$$book HTML</a></li>" \; | sed s:$$book/publish/:: >> index.html ;		 		\
-	      find $$book/publish/$$lang -name html-single -exec echo "<li><a href=\"{}/$$book/index.html\">$$book HTML (single page)</a></li>" \; | sed s:$$book/publish/:: >> index.html ;	\
-	      echo "</ul></li>" >> index.html; 				\
-	    done;							\
-	done
 endif
-	echo "</ol>" >> index.html	
-	echo "<p>You can find <a href=\"http://www.clusterlabs.org/wiki/Documentation\">additional documentation</a> and details about the Pacemaker project at <a href=\"http://www.clusterlabs.org\">http://www.clusterlabs.org</a></p>" >> index.html	
-	echo "</body></html>" >> index.html	
 
+EXTRA_DIST	= $(docbook:%=%.xml)
 
 %.html: %.txt
-	$(ASCIIDOC) --unsafe --backend=xhtml11 $<
+	$(AM_V_ASCII)$(ASCIIDOC) --unsafe --backend=xhtml11 $<
 
-%.txt: %/en-US/*.xml
-	cd $* && $(PUBLICAN) build --publish --langs=all --formats=pdf,html,html-single,txt
+# publican-clusterlabs/xsl/html-single.xsl imports that of Publican
+# through this link during the build
+../xsl:
+	ln -s /usr/share/publican/xsl "$@"
+
+SHARED_TXT=$(wildcard shared/en-US/*.txt)
+SHARED_XML=$(SHARED_TXT:%.txt=%.xml)
+
+
+CFS_SHARED_TXT=$(addprefix shared/en-US/,pacemaker-intro.txt)
+CFS_SHARED_XML=$(CFS_SHARED_TXT:%.txt=%.xml)
+CFS_TXT=$(wildcard Clusters_from_Scratch/en-US/*.txt)
+CFS_XML=$(CFS_TXT:%.txt=%.xml)
+
+$(CFS_XML): $(CFS_SHARED_XML)
+
+# We have to hardcode the book name
+# With '%' the test for 'newness' fails
+Clusters_from_Scratch.build: $(PNGS) $(wildcard Clusters_from_Scratch/en-US/*.xml) $(CFS_XML) $(CFS_SHARED_XML) ../xsl
+	$(PCMK_V) @echo Building $(@:%.build=%) because of $?
+	rm -rf $(@:%.build=%)/publish/*
+	$(AM_V_PUB)cd $(@:%.build=%) && RPM_BUILD_DIR="" $(PUBLICAN) build --publish --langs=$(DOCBOOK_LANGS) --formats=$(DOCBOOK_FORMATS) $(PCMK_quiet) --brand_dir=../publican-clusterlabs
+	rm -rf $(@:%.build=%)/tmp
 	touch $@
 
+
+PE_SHARED_TXT=$(addprefix shared/en-US/,pacemaker-intro.txt)
+PE_SHARED_XML=$(PE_SHARED_TXT:%.txt=%.xml)
+PE_TXT=$(wildcard Pacemaker_Explained/en-US/*.txt)
+PE_XML=$(PE_TXT:%.txt=%.xml)
+
+$(PE_XML): $(PE_SHARED_XML)
+
+# We have to hardcode the book name
+# With '%' the test for 'newness' fails
+Pacemaker_Explained.build: $(PNGS) $(wildcard Pacemaker_Explained/en-US/*.xml) $(PE_XML) $(PE_SHARED_XML) ../xsl
+	$(PCMK_V) @echo Building $(@:%.build=%) because of $?
+	rm -rf $(@:%.build=%)/publish/*
+	$(AM_V_PUB)cd $(@:%.build=%) && RPM_BUILD_DIR="" $(PUBLICAN) build --publish --langs=$(DOCBOOK_LANGS) --formats=$(DOCBOOK_FORMATS) $(PCMK_quiet) --brand_dir=../publican-clusterlabs
+	rm -rf $(@:%.build=%)/tmp
+	touch $@
+
+
+PR_TXT=$(wildcard Pacemaker_Remote/en-US/*.txt)
+PR_XML=$(PR_TXT:%.txt=%.xml)
+
+# We have to hardcode the book name
+# With '%' the test for 'newness' fails
+Pacemaker_Remote.build: $(PNGS) $(wildcard Pacemaker_Remote/en-US/*.xml) $(PR_XML) ../xsl
+	$(PCMK_V) @echo Building $(@:%.build=%) because of $?
+	rm -rf $(@:%.build=%)/publish/*
+	$(AM_V_PUB)cd $(@:%.build=%) && RPM_BUILD_DIR="" $(PUBLICAN) build --publish --langs=$(DOCBOOK_LANGS) --formats=$(DOCBOOK_FORMATS) $(PCMK_quiet) --brand_dir=../publican-clusterlabs
+	rm -rf $(@:%.build=%)/tmp
+	touch $@
+
+# Update the translation template
+pot:
+	for book in $(docbook); do 				      \
+		echo "Updating translation templates in: $$book";     \
+		( cd $$book && RPM_BUILD_DIR="" $(PUBLICAN) update_pot ); \
+	done
+
+# Update the actual translations
+po: pot
+	for book in $(docbook); do 				      \
+		echo "Updating translations in: $$book";     \
+		( cd $$book && RPM_BUILD_DIR="" $(PUBLICAN) update_po --langs=all );\
+	done
+
 if BUILD_DOCBOOK
-docbook_txt = $(docbook:%=%.txt)
+docbook_build = $(docbook:%=%.build)
 
-all-local: $(docbook_txt)
+all-local: $(docbook_build) */publican.cfg
 
-#install-data-local: all-local
-install-data-local: all-local 
+install-data-local: all-local
 	for book in $(docbook); do 							\
-	    filelist=`find $$book/publish -print`;					\
+	    filelist=`find $$book/publish/* -print`;					\
 	    for f in $$filelist; do							\
 		p=`echo $$f | sed s:publish/:: | sed s:Pacemaker/::`;			\
 		if [ -d $$f ]; then							\
-			echo $(INSTALL) -d 775 $(DESTDIR)/$(docdir)/$$p;		\
+			$(INSTALL) -d -m 775 $(DESTDIR)$(docdir)/$$p;			\
 		else									\
-			echo $(INSTALL) -m 644 $$f $(DESTDIR)/$(docdir)/$$p;		\
+			$(INSTALL) -m 644 $$f $(DESTDIR)$(docdir)/$$p;			\
 		fi									\
 	    done;									\
 	done
 endif
 
-push:   all-local $(generated_docs)
-	echo Uploading current documentation set to clusterlabs.org
-	rsync -rtz --progress $(generated_docs) root@oss.clusterlabs.org:/var/www/html/doc/
+brand:  $(BRAND_PNGS) $(wildcard publican-clusterlabs/en-US/*.xml)
+	cd publican-clusterlabs && publican build --formats=xml --langs=all --publish
+	echo "Installing..."
+	cd publican-clusterlabs && sudo publican install_brand --path=$(datadir)/publican/Common_Content
+
+#	find publican-clusterlabs -name "*.noarch.rpm" -exec rm -f \{\} \;
+#	cd publican-clusterlabs && $(PUBLICAN) package --binary
+#	find publican-clusterlabs -name "*.noarch.rpm" -exec sudo rpm -Uvh --force \{\} \;
+
+pdf:
+	make DOCBOOK_FORMATS="pdf" ASCIIDOC_CLI_TYPE=$(ASCIIDOC_CLI_TYPE) all-local
+
+www: clean-local $(generated_docs) $(ascii)
+	make www-cli
+	rsync -rtz --progress $(generated_docs) $(ascii) $(asciiman) $(RSYNC_DEST)
+
+www-pcs: www-cli
+
+www-cli:
+	for book in $(docbook); do 										\
+		sed -i.sed 's@brand:.*@brand: clusterlabs@' $$book/publican.cfg;				\
+		sed -i.sed 's@version:.*@version: $(PACKAGE_SERIES)-$(ASCIIDOC_CLI_TYPE)@' $$book/publican.cfg;	\
+	done
+	make DOCBOOK_FORMATS="pdf,html,html-single,epub" DOCBOOK_LANGS="all" ASCIIDOC_CLI_TYPE=$(ASCIIDOC_CLI_TYPE) all-local
+	echo Uploading current $(PACKAGE_SERIES)-$(ASCIIDOC_CLI_TYPE) documentation set to clusterlabs.org
 if BUILD_DOCBOOK
-	for book in $(docbook); do 							\
-		echo Uploading $$book...;						\
-		echo "Generated on `date` from version: $(BUILD_VERSION)" > $$book/publish/build-$(PACKAGE_SERIES).txt;	\
-		rsync -rtz --progress $$book/publish/* root@oss.clusterlabs.org:/var/www/html/doc/;	\
+	for book in $(docbook); do 									\
+		echo Uploading $$book...;								\
+		echo "Generated on `date` from version: $(shell git log --pretty="format:%h %d" -n 1)" >> $$book/publish/build-$(PACKAGE_SERIES)-$(ASCIIDOC_CLI_TYPE).txt;	\
+		for lang in `ls -1 $$book/publish | grep [a-z][a-z]-[A-Z][A-Z]`; do							\
+			mv $$book/publish/$$lang/Pacemaker/$(PACKAGE_SERIES)-$(ASCIIDOC_CLI_TYPE)/epub/$$book/Pacemaker-1.1{-$(ASCIIDOC_CLI_TYPE),}-$$book-$$lang.epub;	\
+			mv $$book/publish/$$lang/Pacemaker/$(PACKAGE_SERIES)-$(ASCIIDOC_CLI_TYPE)/pdf/$$book/Pacemaker-1.1{-$(ASCIIDOC_CLI_TYPE),}-$$book-$$lang.pdf;	\
+		done;											\
+		rsync -rtz --progress $$book/publish/* $(RSYNC_DEST);					\
+		sed -i.sed 's@version:.*@version: $(PACKAGE_SERIES)@' $$book/publican.cfg;		\
 	done
 endif
 
 clean-local:
-	-rm -rf $(generated_docs) $(docbook)/tmp $(docbook)/publish $(docbook_txt)
+	-rm -rf $(generated_docs) $(generated_mans) $(docbook_build) ../xsl $(generated_PNGS)
+	-rm -rf $(SHARED_XML) $(CFS_XML) $(PE_XML) $(PR_XML)
+	for book in $(docbook); do rm -rf $$book/tmp $$book/publish; done
diff --git a/extra/resources/ping b/extra/resources/ping
--- a/extra/resources/ping
+++ b/extra/resources/ping
@@ -29,7 +29,9 @@
 #######################################################################
 # Initialization:
 
-. ${OCF_ROOT}/resource.d/heartbeat/.ocf-shellfuncs
+: ${OCF_FUNCTIONS=${OCF_ROOT}/resource.d/heartbeat/.ocf-shellfuncs}
+. ${OCF_FUNCTIONS}
+: ${__OCF_ACTION=$1}
 
 #######################################################################
 
@@ -41,8 +43,7 @@ meta_data() {
 <version>1.0</version>
 
 <longdesc lang="en">
-Every time the monitor action is run, this resource agent records (in the CIB) the current number of ping nodes the host can connect to.
-It is essentially the same as pingd except that it uses the system ping tool to obtain the results.
+Every time the monitor action is run, this resource agent records (in the CIB) the current number of nodes the host can connect to using the system fping (preferred) or ping tool.
 </longdesc>
 <shortdesc lang="en">node connectivity</shortdesc>
 
@@ -67,7 +68,7 @@ The time to wait (dampening) further changes occur
 The name of the attributes to set.  This is the name to be used in the constraints.
 </longdesc>
 <shortdesc lang="en">Attribute name</shortdesc>
-<content type="string" default="${OCF_RESOURCE_INSTANCE}"/>
+<content type="string" default="pingd"/>
 </parameter>
 
 <parameter name="multiplier" unique="0">
@@ -75,12 +76,12 @@ The name of the attributes to set.  This is the name to be used in the constrain
 The number by which to multiply the number of connected ping nodes by
 </longdesc>
 <shortdesc lang="en">Value multiplier</shortdesc>
-<content type="integer" default=""/>
+<content type="integer" default="1"/>
 </parameter>
 
-<parameter name="host_list" unique="0">
+<parameter name="host_list" unique="0" required="1">
 <longdesc lang="en">
-The list of ping nodes to count.  Defaults to all configured ping nodes.  Rarely needs to be specified.
+A space separated list of ping nodes to count.
 </longdesc>
 <shortdesc lang="en">Host list</shortdesc>
 <content type="string" default=""/>
@@ -91,7 +92,7 @@ The list of ping nodes to count.  Defaults to all configured ping nodes.  Rarely
 Number of ping attempts, per host, before declaring it dead
 </longdesc>
 <shortdesc lang="en">no. of ping attempts</shortdesc>
-<content type="integer" default="2"/>
+<content type="integer" default="3"/>
 </parameter>
 
 <parameter name="timeout" unique="0">
@@ -108,6 +109,24 @@ A catch all for any other options that need to be passed to ping.
 </longdesc>
 <shortdesc lang="en">Extra Options</shortdesc>
 <content type="string" default=""/>
+</parameter>
+
+<parameter name="failure_score" unique="0">
+<longdesc lang="en">
+Resource is failed if the score is less than failure_score.
+Default never fails.
+</longdesc>
+<shortdesc lang="en">failure_score</shortdesc>
+<content type="integer" default=""/>
+</parameter>
+
+<parameter name="use_fping" unique="0">
+<longdesc lang="en">
+Use fping rather than ping, if found. If set to 0, fping
+will not be used even if present.
+</longdesc>
+<shortdesc lang="en">Use fping if available</shortdesc>
+<content type="boolean" default="1"/>
 </parameter>
 
 <parameter name="debug" unique="0">
@@ -143,7 +162,7 @@ ping_conditional_log() {
 
 ping_usage() {
 	cat <<END
-usage: $0 {start|stop|monitor|migrate_to|migrate_from|validate-all|meta-data}
+usage: $0 {start|stop|monitor|validate-all|meta-data}
 
 Expects to have a fully populated OCF RA-compliant environment set.
 END
@@ -170,13 +189,15 @@ ping_stop() {
 ping_monitor() {
     if [ -f ${OCF_RESKEY_pidfile} ]; then
 	ping_update
-	return $OCF_SUCCESS
+        if [ $? -eq 0 ]; then
+            return $OCF_SUCCESS
+        fi
+        return $OCF_ERR_GENERIC
     fi
     return $OCF_NOT_RUNNING
 }
 
 ping_validate() {
-    
     # Is the state directory writable? 
     state_dir=`dirname "$OCF_RESKEY_pidfile"`
     touch "$state_dir/$$"
@@ -192,14 +213,6 @@ ping_validate() {
 	*) ocf_log warn "You should use an absolute path for pidfile not: $OCF_RESKEY_pidfile" ;;
     esac
     
-# Check the ping interval
-    if ocf_is_decimal "$OCF_RESKEY_CRM_meta_interval" && [ $OCF_RESKEY_CRM_meta_interval -gt 0 ]; then
-	:
-    else
-	ocf_log err "Invalid ping interval $OCF_RESKEY_interval. It should be positive integer!"
-	exit $OCF_ERR_CONFIGURED
-    fi
-
 # Check the host list
     if [ "x" = "x$OCF_RESKEY_host_list" ]; then 
 	ocf_log err "Empty host_list.  Please specify some nodes to ping"
@@ -211,7 +224,37 @@ ping_validate() {
     return $OCF_SUCCESS
 }
 
-ping_update() {
+
+fping_check() {
+    active=0
+    f_out=`mktemp`
+    f_err=`mktemp`
+
+    n=$OCF_RESKEY_attempts
+    timeout=`expr $OCF_RESKEY_timeout \* 1000 / $OCF_RESKEY_attempts`
+
+    cmd="fping -r $OCF_RESKEY_attempts -t $timeout -B 1.0 $OCF_RESKEY_options $OCF_RESKEY_host_list"
+    $cmd>$f_out 2>$f_err; rc=$?
+    active=`grep alive $f_out|wc -l`
+
+    case $rc in
+ 	0) 
+	    ;;
+ 	1) 
+	    for h in `grep unreachable $f_out | awk '{print $1}'`; do
+		ping_conditional_log warn "$h is inactive"
+	    done
+	    ;;
+ 	*) 
+	    ocf_log err "Unexpected result for '$cmd' $rc: `tr '\n' ';' < $f_err`"
+	    ;;
+    esac
+    rm -f $f_out $f_err
+
+    return $active
+}
+
+ping_check() {
     active=0
     for host in $OCF_RESKEY_host_list; do
 	p_exe=ping
@@ -234,6 +277,19 @@ ping_update() {
 	    *) ocf_log err "Unexpected result for '$p_exe $p_args $OCF_RESKEY_options $host' $rc: $p_out";;
 	esac
     done
+    return $active
+}
+
+ping_update() {
+    
+    if ocf_is_true "$OCF_RESKEY_use_fping" && have_binary fping; then
+	fping_check
+	active=$?
+    else
+	ping_check
+	active=$?
+    fi
+
     score=`expr $active \* $OCF_RESKEY_multiplier`
     attrd_updater -n $OCF_RESKEY_name -v $score -d $OCF_RESKEY_dampen $attrd_options
     rc=$?
@@ -241,22 +297,44 @@ ping_update() {
 	0) ping_conditional_log debug "Updated $OCF_RESKEY_name = $score" ;;
 	*) ocf_log warn "Could not update $OCF_RESKEY_name = $score: rc=$rc";;
     esac
-    return $rc
+    if [ $rc -ne 0 ]; then
+        return $rc
+    fi
+
+    if [ -n "$OCF_RESKEY_failure_score" -a "$score" -lt "$OCF_RESKEY_failure_score" ]; then
+        ocf_log warn "$OCF_RESKEY_name is less than failure_score($OCF_RESKEY_failure_score)"
+        return 1
+    fi
+    return 0
 }
 
 : ${OCF_RESKEY_name:="pingd"}
 : ${OCF_RESKEY_dampen:="5s"}
-: ${OCF_RESKEY_attempts:="5"}
+: ${OCF_RESKEY_attempts:="3"}
 : ${OCF_RESKEY_multiplier:="1"}
 : ${OCF_RESKEY_debug:="false"}
-: ${OCF_RESKEY_CRM_meta_timeout:="60"}
-: ${OCF_RESKEY_CRM_meta_interval="10"}
+: ${OCF_RESKEY_failure_score:="0"}
+: ${OCF_RESKEY_use_fping:="1"}
+
+: ${OCF_RESKEY_CRM_meta_timeout:="20000"}
 : ${OCF_RESKEY_CRM_meta_globally_unique:="true"}
 
+integer=`echo ${OCF_RESKEY_timeout} | egrep -o '[0-9]*'`
+case ${OCF_RESKEY_timeout} in
+    *[0-9]ms|*[0-9]msec) OCF_RESKEY_timeout=`expr $integer / 1000`;;
+    *[0-9]m|*[0-9]min) OCF_RESKEY_timeout=`expr $integer \* 60`;;
+    *[0-9]h|*[0-9]hr)  OCF_RESKEY_timeout=`expr $integer \* 60 \* 60`;;
+    *) OCF_RESKEY_timeout=$integer;;
+esac
+
 if [ -z ${OCF_RESKEY_timeout} ]; then
-    host_count=`echo $OCF_RESKEY_host_list | awk '{print NF}'`
-    OCF_RESKEY_timeout=`expr $OCF_RESKEY_CRM_meta_timeout / $host_count / $OCF_RESKEY_attempts`
-    OCF_RESKEY_timeout=`expr $OCF_RESKEY_timeout / 1100` # Convert to seconds and finish 10% early
+    if [ x"$OCF_RESKEY_host_list" != x ]; then
+	host_count=`echo $OCF_RESKEY_host_list | awk '{print NF}'`
+	OCF_RESKEY_timeout=`expr $OCF_RESKEY_CRM_meta_timeout / $host_count / $OCF_RESKEY_attempts`
+	OCF_RESKEY_timeout=`expr $OCF_RESKEY_timeout / 1100` # Convert to seconds and finish 10% early
+    else
+	OCF_RESKEY_timeout=5
+    fi
 fi
 
 if [ ${OCF_RESKEY_timeout} -lt 1 ]; then
diff --git a/extra/resources/pingd b/extra/resources/pingd
--- a/extra/resources/pingd
+++ b/extra/resources/pingd
@@ -30,20 +30,57 @@
 #######################################################################
 # Initialization:
 
-. ${OCF_ROOT}/resource.d/heartbeat/.ocf-shellfuncs
+: ${OCF_FUNCTIONS=${OCF_ROOT}/resource.d/heartbeat/.ocf-shellfuncs}
+. ${OCF_FUNCTIONS}
+: ${__OCF_ACTION=$1}
 
-#######################################################################
+: ${OCF_RESKEY_name:="pingd"}
+: ${OCF_RESKEY_interval:="1"}
+: ${OCF_RESKEY_CRM_meta_interval:=0}
 
-meta_data() {
+upgrade1="This agent (ocf:pacemaker:pingd) has been replaced by the more reliable ocf:pacemaker:ping."
+upgrade2="Attempting automated conversion, run 'crm ra info ocf:pacemaker:ping' for all configuration options"
+upgrade3="You will need to remove the existing resource and replace it with one that uses 'ocf:pacemaker:ping' directly"
+
+case $__OCF_ACTION in
+    start|monitor)
+	if [ "x" != "x$OCF_RESKEY_host_list" ]; then
+	    ocf_log err "$upgrade1"
+	    ocf_log err "$upgrade2"
+	    ocf_log err "Automatic conversion to ocf:pacemaker:ping failed: no hosts were configured to check for connectivity"
+	    ocf_log err "$upgrade3"
+	    exit $OCF_ERR_ARGS
+	fi
+
+	recurring=`crm configure show $OCF_RESOURCE_INSTANCE | grep "op monitor.*interval=\"[1-9]" | sed s/.*interval=// | awk -F\" '{print $2}' | sed s/.*interval=// | awk -F\" '{print $2}' | sort | head -n 1`
+
+	if [ -z $recurring ]; then
+	    ocf_log err "$upgrade1"
+	    ocf_log err "$upgrade2"
+	    ocf_log err "Automatic conversion to ocf:pacemaker:ping failed: no monitor operation configured"
+	    ocf_log err "Without an explicit monitor operation for '$OCF_RESOURCE_INSTANCE', connectivity changes will not be noticed"
+	    ocf_log err "Preventing startup to ensure the issue is addressed before it matters"
+	    exit $OCF_ERR_ARGS
+	fi
+	
+	if [ $OCF_RESKEY_CRM_meta_interval = 0 ]; then
+	    ocf_log warn "$upgrade1"
+	    ocf_log warn "$upgrade2"
+	    if [ $recurring != $OCF_RESKEY_interval ]; then
+		ocf_log warn "Your monitor operation happens every $recurring, which means that the $OCF_RESKEY_name attribute will be updated with a different frequency than the previously configured ( $OCF_RESKEY_interval )"
+		ocf_log warn "Either change the monitor interval to match or, ideally, switch to the ocf:pacemaker:ping agent and avoid all this compatibility nonsense."
+	    fi
+	fi
+	;;
+    meta-data)
 	cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
 <resource-agent name="pingd">
 <version>1.0</version>
-
 <longdesc lang="en">
-This is a pingd Resource Agent.
-It records (in the CIB) the current number of ping nodes a node can connect to.
+This agent (ocf:pacemaker:pingd) has been replaced by the more reliable ocf:pacemaker:ping.
+It records (in the CIB) the current number of ping nodes (specified in the 'host_list' parameter) a cluster node can connect to.
 </longdesc>
 <shortdesc lang="en">pingd resource agent</shortdesc>
 
@@ -85,7 +122,7 @@ The name of the instance_attributes set to place the value in.  Rarely needs to 
 The name of the attributes to set.  This is the name to be used in the constraints.
 </longdesc>
 <shortdesc lang="en">Attribute name</shortdesc>
-<content type="string" default="${OCF_RESOURCE_INSTANCE}"/>
+<content type="string" default="pingd"/>
 </parameter>
 
 <parameter name="section" unique="0">
@@ -155,156 +192,9 @@ A catch all for any other options that need to be passed to pingd.
 </actions>
 </resource-agent>
 END
-}
-
-#######################################################################
-
-pingd_usage() {
-	cat <<END
-usage: $0 {start|stop|monitor|validate-all|meta-data}
-
-Expects to have a fully populated OCF RA-compliant environment set.
-END
-}
-
-pingd_start() {
-    extras=""
-    if [ ! -z "$OCF_RESKEY_multiplier" ]; then
-	extras="$extras -m $OCF_RESKEY_multiplier"
-    fi
-    if [ ! -z "$OCF_RESKEY_set" ]; then
-	extras="$extras -s $OCF_RESKEY_set"
-    fi
-    if [ ! -z "$OCF_RESKEY_section" ]; then
-	extras="$extras -S $OCF_RESKEY_section"
-    fi
-    if [ ! -z "$OCF_RESKEY_interval" ]; then
-        extras="$extras -i $OCF_RESKEY_interval"
-    fi
-    if [ ! -z "$OCF_RESKEY_attempts" ]; then
-        extras="$extras -n $OCF_RESKEY_attempts"
-    fi
-    if [ ! -z "$OCF_RESKEY_timeout" ]; then
-        extras="$extras -t $OCF_RESKEY_timeout"
-    fi
-    for a_host in $OCF_RESKEY_host_list; do
-	extras="$extras -h $a_host"
-    done
-    pingd_cmd="${HA_BIN}/pingd -D -p $OCF_RESKEY_pidfile -a $OCF_RESKEY_name -d $OCF_RESKEY_dampen $extras $OCF_RESKEY_options"
-
-    if [ ! -z $OCF_RESKEY_user ]; then
-	sudo -u $OCF_RESKEY_user $pingd_cmd
-    else
-	$pingd_cmd
-    fi
-
-    rc=$?
-    if [ $rc = 0 ]; then
 	exit $OCF_SUCCESS
-    fi
-    
-    ocf_log err "Could not run $pingd_cmd : rc=$rc"
-    exit $OCF_ERR_GENERIC
-}
-
-pingd_stop() {
-    if [ -f $OCF_RESKEY_pidfile ]; then
-	pid=`cat $OCF_RESKEY_pidfile`
-    fi
-    if [ ! -z $pid ]; then
-	kill -TERM $pid
-	rc=$?
-
-	if [ $rc = 0 -o $rc = 1 ]; then
-	    rm $OCF_RESKEY_pidfile
-	    exit $OCF_SUCCESS
-	fi
-
-	ocf_log err "Unexpected result from kill -TERM $pid: $rc"
-	exit $OCF_ERR_GENERIC
-    fi
-    exit $OCF_SUCCESS
-}
-
-pingd_monitor() {
-    if [ -f $OCF_RESKEY_pidfile ]; then
-	pid=`cat $OCF_RESKEY_pidfile`
-    fi
-    if [ ! -z $pid ]; then
-	kill -0 $pid
-	if [ $? = 0 ]; then
-	    exit $OCF_SUCCESS
-	fi
-    fi
-    exit $OCF_NOT_RUNNING
-}
-
-pingd_validate() {
-# Existence of the user
-    if [ ! -z $OCF_RESKEY_user ]; then
-	getent passwd "$OCF_RESKEY_user" >/dev/null
-	if [ $? -eq 0 ]; then
-	    : Yes, user exists. We can further check his permission on crm_mon if necessary
-	else
-	    ocf_log err "The user $OCF_RESKEY_user does not exist!"
-	    exit $OCF_ERR_ARGS
-	fi
-    fi
-
-# Pidfile better be an absolute path
-    case $OCF_RESKEY_pidfile in
-	/*) ;;
-	*) ocf_log warn "You should have pidfile($OCF_RESKEY_pidfile) of absolute path!" ;;
-    esac
-
-# Check the ping interval
-    if ocf_is_decimal "$OCF_RESKEY_interval" && [ $OCF_RESKEY_interval -gt 0 ]; then
-	:
-    else
-	ocf_log err "Invalid ping interval $OCF_RESKEY_interval. It should be positive integer!"
-	exit $OCF_ERR_ARGS
-    fi
-
-    echo "Validate OK"
-    return $OCF_SUCCESS
-}
-
-if [ $# -ne 1 ]; then
-    pingd_usage
-    exit $OCF_ERR_ARGS
-fi
-
-: ${OCF_RESKEY_options:=""}
-: ${OCF_RESKEY_dampen:="5s"}
-: ${OCF_RESKEY_interval:="1"}
-: ${OCF_RESKEY_name:="pingd"}
-: ${OCF_RESKEY_CRM_meta_interval:=0}
-: ${OCF_RESKEY_CRM_meta_globally_unique:="true"}
-
-if [ ${OCF_RESKEY_CRM_meta_globally_unique} = "false" ]; then
-    : ${OCF_RESKEY_pidfile:="$HA_VARRUN/pingd-${OCF_RESKEY_name}"}
-else 
-    : ${OCF_RESKEY_pidfile:="$HA_VARRUN/pingd-${OCF_RESOURCE_INSTANCE}"}
-fi
-
-case $__OCF_ACTION in
-meta-data)	meta_data
-		exit $OCF_SUCCESS
-		;;
-start)		pingd_start
-		;;
-stop)		pingd_stop
-		;;
-monitor)	pingd_monitor
-		;;
-validate-all)	pingd_validate
-		;;
-usage|help)	pingd_usage
-		exit $OCF_SUCCESS
-		;;
-*)		pingd_usage
-		exit $OCF_ERR_UNIMPLEMENTED
-		;;
+	;;
 esac
 
+${OCF_ROOT}/resource.d/pacemaker/ping $1
 exit $?
diff --git a/tools/crm_failcount b/tools/crm_failcount
--- a/tools/crm_failcount
+++ b/tools/crm_failcount
@@ -1,9 +1,10 @@
 #!/bin/bash
 
+resource=""
 options=""
-target=`uname -n`
+target=`crm_node -n`
 
-TEMP=`getopt -o DGQVN:U:v:i:l:r: --long resource-id:,node:,uname:,attr-value:,delete-attr,get-value,attr-id:,lifetime:,quiet \
+TEMP=`getopt -o DGQVN:U:v:i:l:r: --long help,version,resource-id:,node:,uname:,attr-value:,delete-attr,get-value,attr-id:,lifetime:,quiet \
      -n 'crm_failcount' -- "$@"`
 
 if [ $? != 0 ] ; then echo "crm_failcount - A convenience wrapper for crm_attribute"; echo ""; crm_attribute -?; exit 1 ; fi
@@ -11,16 +12,51 @@ if [ $? != 0 ] ; then echo "crm_failcount - A convenience wrapper for crm_attrib
 # Note the quotes around `$TEMP': they are essential!
 eval set -- "$TEMP"
 
+function show_help() {
+	    echo "crm_failcount - A convenience wrapper for crm_attribute";
+	    echo "";
+	    echo "Set, update or remove the failcount for the specified resource on the named node";
+	    echo "";
+	    echo "Usage: crm_failcount -r resource_name command [options]";
+	    echo "Options:"
+	    echo " --help 		This text"
+	    echo " --version 		Version information"
+	    echo " -V, --verbose 		Increase debug output"
+	    echo " -q, --quiet 		Print only the value on stdout"
+	    echo ""
+	    echo " -r, --resource-id=value	The resource to update."
+	    echo ""
+	    echo "Commands:"
+	    echo " -G, --query 		Query the current value of the attribute/option"
+	    echo " -v, --update=value	Update the value of the attribute/option"
+	    echo " -D, --delete 		Delete the attribute/option"
+	    echo ""
+	    echo "Additional Options:"
+	    echo " -N, --node=value	Set an attribute for the named node (instead of the current one)."
+	    echo " -l, --lifetime=value	Until when should the setting take affect."
+	    echo "	       		Valid values: reboot, forever"
+	    echo " -i, --id=value		(Advanced) The ID used to identify the attribute"
+}
+
 while true ; do
     case "$1" in
 	-N|--node) target="$2"; shift; shift;;
 	-U|--uname) target="$2"; shift; shift;;
 	-v|--attr-value|-i|--attr-id) options="$options $1 $2"; shift; shift;;
 	-Q|--quiet|-D|--delete-attr|-G|--get-value|-V) options="$options $1"; shift;;
-	-r|--resource-id) options="$options -n fail-count-$2"; shift; shift;;
+	-r|--resource-id) options="$options -n fail-count-$2"; resource="$2"; shift; shift;;
+	--version) crm_attribute --version; exit 0;;
+	--help)
+	    show_help
+	    exit 0;;
 	--) shift ; break ;;
-	*) echo "crm_failcount - A convenience wrapper for crm_attribute"; echo ""; crm_attribute -?; exit 1;;
+	*) echo "Unknown option: $1. See --help for details." exit 1;;
     esac
 done
+
+if [ "x$resource" = x ]; then
+    echo "You must supply a resource name to check. See 'crm_failcount --help' for details"
+    exit 1
+fi
 
 crm_attribute -N $target $options -t status -d 0
